### ISSUE TITLE
Close at startup Xbian 20.2 Nexus.

### ISSUE THREAD

**Issue by DREU007** [basilgello/Transmission-Control-Panel#4]
Transmission immediately close after start. For a second UI is visible and then an error appears.

> Transmission Error

```
Could not connect to Transmission
Open settings dialog?
```

The package was installed from the default repository.  Attempt to change kernel to 32 (kernel: 6.1.38+) doesn't made any difference. 

System:
Transmission Control Panel 1.0.2
Raspberry Pi 4 8Gb
XBian 11.0 - Bookworm (kernel: Linux 6.13.38-64+ aarhc64)
Build: 20.2 (20.2.0)

**Comment by basilgello** [comment]
Is transmission-daemon running at the time you try reaching it with Kodi?

**Comment by DREU007** [comment]
Problem solved. 

Exited Kodi and entered tty, updated packages and reinstalled transmission-daemon. Thx for showing the right direction.
